
openapi: 3.0.1
info:
  title: MSAC NRM
  version: 18.0.0
  description: >-
    OAS 3.0.1 definition of the MSAC NRM
    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 28.319; MSAC NRM
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.319/
paths: {}
components:
  schemas:

#-------- Definition of types-----------------------------------------------------

#-------- Definition of concrete IOCs --------------------------------------------

    Identity-Single:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                identityType:
                    type: string
                    enum:
                      - USERNAME
                      - EMAIL_ADDRESS
                      - PHONE_NUMBER
                      - IP_ADDRESS
                      - MACHINEUSER
                identityName:
                  type: string
                credential:
                  type: string
                roleRefList:
                  $ref: 'TS28623_ComDefs.yaml#/components/schemas/DnList'

    Role-Single:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              type: object
              properties:
                roleName:
                  type: string
                accessRulesList:
                  $ref: 'TS28623_ComDefs.yaml#/components/schemas/DnList'
                  
    AccessRule-Single:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes: 
              type: object  
              properties:
                ruleName:
                  type: string
                resources:
                  type: string
                operations:
                  type: array
                  items: 
                    type: string
                actions:
                  type: string
                  enum:
                    - ALLOW
                    - DENY
                componentCData:
                  type: array
                  items: 
                    type: string
                
    resources-msacNrm:
      oneOf:
        - $ref: '#/components/schemas/Identity-Single'
        - $ref: '#/components/schemas/Role-Single'
        - $ref: '#/components/schemas/AccessRule-Single'
