openapi: 3.0.0

info:
  title: NSCE Server Network Slice Optimization Service
  version: 1.0.0-alpha.3
  description: |
    NSCE Server Network Slice Optimization Service.  
    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.

externalDocs:
  description: >
    3GPP TS 29.435 V18.0.0; Service Enabler Architecture Layer for Verticals (SEAL);
    Network Slice Capability Exposure (NSCE) Server Service(s); Stage 3.
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.435/

servers:
  - url: '{apiRoot}/nsce-nso/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 6.5 of 3GPP TS 29.549.

security:
  - {}
  - oAuth2ClientCredentials: []

paths:
  /subscriptions:
    post:
      summary: Request the creation of a Network Slice Optimization Subscription.
      operationId: CreateNetSliceOptSubsc
      tags:
        - Network Slice Optimization Subscriptions (Collection)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetSliceOptSubsc'
      responses:
        '201':
          description: >
            Created. The Network Slice Optimization Subscription is successfully created and
            a representation of the created Individual Network Slice Optimization 
            Subscription resource shall be returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetSliceOptSubsc'
          headers:
            Location:
              description: >
                Contains the URI of the created Individual Network Slice Optimization
                Subscription resource.
              required: true
              schema:
                type: string
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
      callbacks:
        NetSliceOptNotif:
          '{$request.body#/notifUri}':
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/NetSliceOptNotif'
              responses:
                '204':
                  description: >
                    No Content. The Network Slice Optimization Notification is successfully
                    received and acknowledged.
                '307':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/307'
                '308':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/308'
                '400':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/400'
                '401':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/401'
                '403':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/403'
                '404':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/404'
                '411':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/503'
                default:
                  $ref: 'TS29122_CommonData.yaml#/components/responses/default'

  /subscriptions/{subscriptionId}:
    parameters:
      - name: subscriptionId
        in: path
        description: >
          Represents the identifier of the Individual Network Slice Optimization
          Subscription resource.
        required: true
        schema:
          type: string

    get:
      summary: Retrieve an existing Individual Network Slice Optimization Subscription resource.
      operationId: GetIndNetSliceOptSubsc
      tags:
        - Individual Network Slice Optimization Subscription (Document)
      responses:
        '200':
          description: >
            OK. The requested Individual Network Slice Optimization Subscription resource shall
            be returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetSliceOptSubsc'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    put:
      summary: Request the fully update of an existing Individual Network Slice Optimization Subscription resource.
      operationId: UpdateIndNetSliceOptSubsc
      tags:
        - Individual Network Slice Optimization Subscription (Document)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetSliceOptSubsc'
      responses:
        '200':
          description: >
            OK. The Individual Network Slice Optimization Subscription resource is
            successfully updated and a representation of the updated resource shall be returned
            in the response body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetSliceOptSubsc'
        '204':
          description: >
            No Content. The Individual Network Slice Optimization Subscription resource is
            successfully updated and no content is returned in the response body.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    patch:
      summary: Request the partially update of an existing Individual Network Slice Optimization Subscription resource.
      operationId: ModifyIndNetSliceOptSubsc
      tags:
        - Individual Network Slice Optimization Subscription (Document)
      requestBody:
        required: true
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/NetSliceOptSubscPatch'
      responses:
        '200':
          description: >
            OK. The Individual Network Slice Optimization Subscription resource is
            successfully modified and a representation of the updated resource shall be returned
            in the response body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetSliceOptSubsc'
        '204':
          description: >
            No Content. The Individual Network Slice Optimization Subscription resource is
            successfully modified and no content is returned in the response body.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    delete:
      summary: Request the deletion of an existing Individual Network Slice Optimization Subscription resource.
      operationId: DeleteIndNetSliceOptSubsc
      tags:
        - Individual Network Slice Optimization Subscription (Document)
      responses:
        '204':
          description: >
            No Content. The Individual Network Slice Optimization Subscription resource is
            successfully deleted.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'


components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}

  schemas:

#
# STRUCTURED DATA TYPES
#

    NetSliceOptSubsc:
      type: object
      description: Represents a Network Slice Optimization subscription.
      properties:
        notifUri:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        netSliceId:
          $ref: 'TS29435_NSCE_PolicyManagement.yaml#/components/schemas/NetSliceId'
        dnn:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnn'
        policyId:
          type: string
          description: Identifies the VAL server policy.
        expTime:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/DateTime'
        secPolicId:
          type: string
          description: Identifies the the secondary policy for the network slice optimization.
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - notifUri
      anyOf:
        - required: [netSliceId]
        - required: [dnn]
        - required: [policyId]
        - required: [expTime]
        - required: [secPolicId]

    NetSliceOptSubscPatch:
      type: object
      description: >
        Represents the requested modifications to a Network Slice Optimization subscription.
      properties:
        notifUri:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        netSliceId:
          $ref: 'TS29435_NSCE_PolicyManagement.yaml#/components/schemas/NetSliceId'
        dnn:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnn'
        policyId:
          type: string
          description: Identifies the VAL server policy.
        expTime:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/DateTimeRm'
        secPolicId:
          type: string
          description: Identifies the the secondary policy for the network slice optimization.
      required:
        - notifUri
      anyOf:
        - required: [netSliceId]
        - required: [dnn]
        - required: [policyId]
        - required: [expTime]
        - required: [secPolicId]

    NetSliceOptNotif:
      type: object
      description: Represents a Network Slice Optimization notification.
      properties:
        subscriptionId:
          type: string
          description: Identifies the Network slice optimization subscribe event.
        sliceInfo:
          $ref: 'TS29435_NSCE_NSInfoDelivery.yaml#/components/schemas/NSInfoSet'
        optTime:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DurationSec'
        enforPolId:
          type: string
          description: Indicates the policy used for slice optimization.
      required:
        - subscriptionId
        - sliceInfo
