openapi: 3.0.0

info:
  title: NSCE Server Network Slice Fault Diagnosis Service
  version: 1.0.0-alpha.3
  description: |
    NSCE Server Network Slice Fault Diagnosis Service.  
    © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.

externalDocs:
  description: >
    3GPP TS 29.435 V18.0.0; Service Enabler Architecture Layer for Verticals (SEAL);
    Network Slice Capability Exposure (NSCE) Server Service(s); Stage 3.
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.435/

servers:
  - url: '{apiRoot}/nsce-fd/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 6.5 of 3GPP TS 29.549.

security:
  - {}
  - oAuth2ClientCredentials: []

paths:
  /subscriptions:
    post:
      summary: Request the creation of a Network Slice Fault Diagnosis Subscription.
      operationId: CreateFaultDiagSubsc
      tags:
        - Network Slice Fault Diagnosis Subscriptions (Collection)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FaultDiagSubsc'
      responses:
        '201':
          description: >
            Created. The Network Slice Fault Diagnosis Subscription is successfully created
            and a representation of the created Individual Network Slice Fault Diagnosis
            Subscription resource shall be returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FaultDiagSubsc'
          headers:
            Location:
              description: >
                Contains the URI of the created Individual Network Slice Fault Diagnosis
                Subscription resource.
              required: true
              schema:
                type: string
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
      callbacks:
        FaultDiagNotif:
          '{$request.body#/notifUri}':
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/FaultDiagNotif'
              responses:
                '204':
                  description: >
                    No Content. The Network Slice Fault Diagnosis Notification is successfully
                    received and acknowledged.
                '307':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/307'
                '308':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/308'
                '400':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/400'
                '401':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/401'
                '403':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/403'
                '404':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/404'
                '411':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/503'
                default:
                  $ref: 'TS29122_CommonData.yaml#/components/responses/default'

  /subscriptions/{subscriptionId}:
    parameters:
      - name: subscriptionId
        in: path
        description: >
          Represents the identifier of the Individual Network Slice Fault Diagnosis
          Subscription resource.
        required: true
        schema:
          type: string

    get:
      summary: Retrieve an existing Individual Network Slice Fault Diagnosis Subscription resource.
      operationId: GetIndFaultDiagSubsc
      tags:
        - Individual Network Slice Fault Diagnosis Subscription (Document)
      responses:
        '200':
          description: >
            OK. The requested Individual Network Slice Fault Diagnosis Subscription resource shall
            be returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FaultDiagSubsc'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    put:
      summary: Request the fully update of an existing Individual Network Slice Fault Diagnosis Subscription resource.
      operationId: UpdateIndFaultDiagSubsc
      tags:
        - Individual Network Slice Fault Diagnosis Subscription (Document)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FaultDiagSubsc'
      responses:
        '200':
          description: >
            OK. The Individual Network Slice Fault Diagnosis Subscription resource is
            successfully updated and a representation of the updated resource shall be returned
            in the response body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FaultDiagSubsc'
        '204':
          description: >
            No Content. The Individual Network Slice Fault Diagnosis Subscription resource is
            successfully updated and no content is returned in the response body.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    patch:
      summary: Request the partially update of an existing Individual Network Slice Fault Diagnosis Subscription resource.
      operationId: ModifyIndFaultDiagSubsc
      tags:
        - Individual Network Slice Fault Diagnosis Subscription (Document)
      requestBody:
        required: true
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/FaultDiagSubscPatch'
      responses:
        '200':
          description: >
            OK. The Individual Network Slice Fault Diagnosis Subscription resource is
            successfully modified and a representation of the updated resource shall be returned
            in the response body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FaultDiagSubsc'
        '204':
          description: >
            No Content. The Individual Network Slice Fault Diagnosis Subscription resource is
            successfully modified and no content is returned in the response body.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    delete:
      summary: Request the deletion of an existing Individual Network Slice Fault Diagnosis Subscription resource.
      operationId: DeleteIndFaultDiagSubsc
      tags:
        - Individual Network Slice Fault Diagnosis Subscription (Document)
      responses:
        '204':
          description: >
            No Content. The Individual Network Slice Fault Diagnosis Subscription resource is
            successfully deleted.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'


components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}

  schemas:

#
# STRUCTURED DATA TYPES
#

    FaultDiagSubsc:
      type: object
      description: Represents a Network Slice Fault Diagnosis subscription.
      properties:
        notifUri:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        valServId:
          type: string
          description: >
            Contains the identifier of the VAL Service to which the fault diagnosis is related.
        valUeIds:
          type: array
          items:
            type: string
          description: >
            Contains the list of the identifier(s) of the VAL UE(s) to which the subscription
            is related.
          minItems: 1
        netSliceIds:
          type: array
          items:
            $ref: 'TS29435_NSCE_PolicyManagement.yaml#/components/schemas/NetSliceId'
          description: Contains the identifier(s) of the network slice to be monitored.
          minItems: 1
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - notifUri
        - valServId

    FaultDiagSubscPatch:
      type: object
      description: >
        Represents the requested modifications to a Network Slice Fault Diagnosis subscription.
      properties:
        notifUri:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        valUeIds:
          type: array
          items:
            type: string
          description: >
            Contains the list of the identifier(s) of the VAL UE(s) to which the subscription
            is related.
          minItems: 1
        netSliceIds:
          type: array
          items:
            $ref: 'TS29435_NSCE_PolicyManagement.yaml#/components/schemas/NetSliceId'
          description: Contains the updated identifier(s) of the network slice to be monitored.
          minItems: 1

    FaultDiagNotif:
      type: object
      description: Represents a Network Slice Fault Diagnosis notification.
      properties:
        subscriptionId:
          type: string
          description: >
            Contains the identifier of the subscription to which the Network Slice Fault
            Diagnosis Notification is related.
        faultRep:
          $ref: '#/components/schemas/FaultReportInfo'
      required:
        - subscriptionId
        - faultRep

    FaultReportInfo:
      type: object
      description: Represents the report of the fault diagnosis.
      properties:
        corelAlarm:
          type: array
          items:
            $ref: '#/components/schemas/CorrelatedAlarm'
          description: >
            Contains the list of the correlated alarms.
          minItems: 1
      required:
        - corelAlarm

    CorrelatedAlarm:
      type: object
      description: Represents the correlated alarm information.
      properties:
        alarmType:
          $ref: '#/components/schemas/AlarmType'
        priority:
          $ref: '#/components/schemas/Priority'
        rootCause:
          type: boolean
          description: Indicates whether the event is the root cause of the events.
      required:
        - alarmType


#
# ENUMERATIONS
#

    AlarmType:
      anyOf:
      - type: string
        enum:
           - COMMUNICATIONS_ALARM
           - PROCESSING_ERROR_ALARM
           - ENVIRONMENTAL_ALARM
           - QUALITY_OF_SERVICE_ALARM
           - EQUIPMENT_ALARM
           - INTEGRITY_VIOLATION
      - type: string
        description: >
          This string provides forward-compatibility with future extensions to the enumeration
          and is not used to encode content defined in the present version of this API.
      description: |
        Represents the alarm type(s).  
        Possible values are:
        - COMMUNICATIONS_ALARM: An alarm associated with the procedures and/or processes required
          to convey information from one point to another.
        - PROCESSING_ERROR_ALARM: An alarm associated with a software or processing fault.
        - ENVIRONMENTAL_ALARM: An alarm associated with a condition relating to an enclosure in
          which the equipment resides.
        - QUALITY_OF_SERVICE_ALARM: An alarm associated with a degradation in the quality of a
          service.
        - EQUIPMENT_ALARM: An alarm associated with an equipment fault.
        - INTEGRITY_VIOLATION: An indication that information may have been illegally modified,
          inserted or deleted.

    Priority:
      anyOf:
      - type: string
        enum:
           - CRITICAL
           - MAJOR
           - MINOR
           - IGNORE
      - type: string
        description: >
          This string provides forward-compatibility with future extensions to the enumeration
          and is not used to encode content defined in the present version of this API.
      description: |
        Represents the prioritization of the fault associated with the correlated alarm.  
        Possible values are:
        - CRITICAL: Indicates the prioritization of the fault is critical.
        - MAJOR: Indicates the prioritization of the fault is major.
        - MINOR: Indicates the prioritization of the fault is minor.
        - IGNORE: Indicates the prioritization of the fault is ignore.
